project:
  type: website
  output-dir: docs

website:
  title: " "
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: CV
      - href: Pub.qmd
        text: Publications
      - href: Talks.qmd
        text: Communications
      - href: Teach.qmd
        text: Enseignements
      - href: Blog.qmd
        text: Blog
      
    tools:
      - icon: linkedin
        href: "https://www.linkedin.com/in/adama-ibrahim-barry-253314133/"
      - icon: github
      - menu:
         - text: "GitPerso"
           href: "https://github.com/barryadama"
         - text: "GitPhD"
           href: "https://github.com/TheseAdama"

format:
  html:
    theme:
      light: spacelab #sandstone spacelab lumen flatly litera
      dark: cyborg #darkly #cyborg
    toggle: true
    mainfont: "Helvetica Neue"
    sansfont: "Helvetica Neue"
    monofont: "Menlo"
    color-scheme: light dark
    css: styles.css


editor: visual
execute:
  python: quarto-env/Scripts/python.exe