---
title: " "
---

## Publication

[Plans d'expériences pour la calibration de codes de calcul](https://theses.hal.science/UNIV-UT3/hal-04615127v2)

*Date : 24 juin 2024 - Publié sur : HAL et soumis sur IJUQ*

**Résumé :** Dans ce travail, nous abordons le problème de la calibration bayésienne d’un code de calcul coûteux, supposé sans écart de modèle. Dans un processus de calibration impliquant à la fois une acquisition coûteuse de mesures physiques et un temps de calcul élevé du code, la précision de l’estimation et la réduction des coûts doivent guider la sélection des plans d’expériences physiques et numériques.

À cette fin, nous proposons une stratégie unifiée pour sélectionner à la fois les plans d’expériences physiques et numériques, dans le but d’approximer la densité a posteriori des paramètres de calibration. Nous construisons d’abord un émulateur initial par processus gaussien, qui est utilisé pour calculer un critère d’optimalité pour la conception des expériences physiques. Ensuite, nous combinons les observations physiques avec les évaluations disponibles du code de calcul afin d’ajouter séquentiellement de nouveaux points au plan d’expériences numériques, dans le but d’améliorer l’émulateur de processus gaussien pour l'objectif de calibration.

Nous introduisons de nouveaux critères d’optimalité pour la sélection du plan d’expériences physiques, basés soit sur la densité a posteriori, soit sur la variabilité du code de calcul en fonction des paramètres, ainsi qu’une nouvelle fonction d’acquisition pour la sélection du plan d’expériences numériques, inspirée du paradigme de Réduction Séquentielle de l’Incertitude (SUR).

Une illustration et une analyse des performances, ainsi qu’une comparaison avec une approche de type space-filling, sont réalisées dans quatre configurations : deux cas tests analytiques, un exemple portant sur la calibration d’un oscillateur harmonique, et une application plus réaliste portant sur la calibration du modèle Level E.

------------------------------------------------------------------------

## Thèse de Doctorat

[**Plans d'expériences pour la calibration de codes de calcul coûteux**](https://theses.hal.science/tel-05186532/)

*Date : 25 juin 2025 — Publié sur : HAL*

**Résumé :** Dans cette thèse, nous étudions le problème de calibration bayésienne de codes de calculs coûteux, à sortie scalaire, vectorielle ou fonctionnelle, à l'aide de données physiques en nombre limité. Un code de calculs est dit coûteux lorsque son évaluation requiert un temps de calcul important. Dans ce contexte, l'inférence bayésienne sur ses paramètres nécessite l'utilisation d'un émulateur ou modèle de substitution. 

Nous introduisons une stratégie en deux étapes combinant une sélection optimale du plan d'expériences physiques (pour les mesures physiques à effectuer sur le terrain) et du plan d'expériences numériques (pour la construction de l'émulateur par processus gaussien). La première phase consiste à construire un émulateur initial par processus gaussien, qui servira au calcul des critères d'optimalité du plan d'expériences physiques. Deux types de critères sont introduits. D'une part, des critères bayésiens basés sur la distribution a posteriori des paramètres de calibration. Ces critères ont la particularité de prendre en compte l'ensemble des incertitudes, qu'elles soient liées aux observations physiques, numériques ou aux paramètres du code de calculs. D'autre part, un critère utilisant la variation du code en fonction de ses paramètres combiné à la répartition du plan dans l'espace expérimental. Ce dernier se distingue par son coût d'optimisation réduit. Pour optimiser ces critères, quatre algorithmes sont proposés : le recuit simulé, un algorithme glouton, un algorithme génétique et un algorithme d'optimisation stochastique par perturbation simultanée. Après acquisition des données physiques, l'émulateur est amélioré par une planification séquentielle d'expériences numériques, guidée par un critère d'acquisition visant une réduction progressive de l'incertitude de calibration. Deux critères d'acquisition, exclusivement dédiés à la calibration, ont été définis : le premier repose sur la somme des variances a posteriori des paramètres de calibration et le second est basé sur l'erreur de prédiction des observations physiques. L'émulateur final est ensuite utilisé pour approcher la densité a posteriori des paramètres à l'aide d'un échantillonnage Monte Carlo par chaînes de Markov, couplé à une estimation non paramétrique par noyaux. Une application numérique sur des fonctions analytiques à sortie scalaire a permis d'évaluer la pertinence des critères et des stratégies de planification d'expériences numériques, en les comparant à d'autres approches de l'état de l'art. De plus, une adaptation de la méthodologie de calibration aux codes de calculs à sortie vectorielle ou fonctionnelle est proposée. 

Enfin, la méthodologie a été appliquée à la calibration d'un simulateur numérique dédié au stockage géologique du CO2, en utilisant des données synthétiques.
